INCLUDE_UTILS=0
include ../common/config.mk

TARGET = uitest
LDFLAGS := $(LDFLAGS) -s -lSDL -lSDL_image -lSDL_ttf
# CPPFILES := $(CPPFILES)

include ../common/commands.mk
include ../common/recipes.mk
