INCLUDE_CJSON=1
OFILES := $(OFILES) ../common/utils/msleep.o
include ../common/config.mk

TARGET = chargingState
LDFLAGS := $(LDFLAGS) -s -lSDL -lSDL_image -lSDL_ttf

include ../common/commands.mk
include ../common/recipes.mk
