INCLUDE_CJSON=1
include ../common/config.mk

TARGET = infoPanel
LDFLAGS := $(LDFLAGS) -lSDL -lSDL_ttf -lSDL_image -lSDL_mixer -lSDL_rotozoom

include ../common/commands.mk
include ../common/recipes.mk
