INCLUDE_CJSON=1
include ../common/config.mk

TARGET = gameSwitcherModInstaller
LDFLAGS := $(LDFLAGS) -lSDL -lSDL_image -lSDL_ttf -lSDL_mixer -lSDL_rotozoom -lpng

include ../common/commands.mk
include ../common/recipes.mk
