blank_issues_enabled: false
contact_links:
  - name: 'Get help, request a feature or ask questions from the Miyoo Mini community on Discord'
    url: https://discord.com/channels/529983248114122762/891336865540620338/
    about: 'Join the discord channel for community-powered support (1,500+ members, very active)! To join the server go here: https://discord.gg/Jd2azKX'
  - name: 'Get help or ask questions from the Miyoo Mini community on Reddit'
    url: https://www.reddit.com/r/MiyooMini/
    about: 'Join the subreddit for community-powered support (5,000+ members, very active)!'
