name: "Wiki Documentation Update Request"
description: Help us improve the Onion Wiki - Report something incorrect or missing
title: "Wiki Update Title"
labels: ["documentation"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this Wiki update Request!

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following in order to prevent misuse of issues
      options:
        - label: I have reviewed the [Onion Wiki](https://github.com/OnionUI/Onion/wiki) and something is incorrect or missing
          required: true
  - type: input
    id: os
    attributes:
      label: Wiki Section
      description: Section to be Updated  
      placeholder: Provide the section name or page name or a URL
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please tell us what is incorrect or missing
      placeholder: Provide a clear and concise description of what is wrong and why
    validations:
      required: true
  - type: textarea
    id: correction
    attributes:
      label: Correction
      description: Please tell us what it should say instead
      placeholder: Provide details of the suggested correction
      value: 
    validations:
      required: true
  - type: textarea
    id: Context
    attributes:
      label: Provide any additional context or information that may help us with this update
      description: You may attach any pictures or files if applicable  
      placeholder: This field is optional
    validations:
      required: false
