#!/bin/sh

cat /proc/ls
sleep 0.25

cd $(dirname "$0")

keymon &

touch /tmp/MainUI_exec && sync
while [ -f /tmp/MainUI_exec ]; do

cd /mnt/SDCARD/miyoo/app
./MainUI

if [ -f /tmp/.cmdenc ] ; then
    /root/gameloader
    elif [ -f /tmp/cmd_to_run.sh ] ; then
        chmod a+x /tmp/cmd_to_run.sh
        /tmp/cmd_to_run.sh
        rm /tmp/cmd_to_run.sh
    fi

if [ -f /mnt/SDCARD/App/AutoShutdown/data/.enabled ] ; then
    reboot
fi
# First time launch
cd /mnt/SDCARD/App/AutoShutdown/data
if [ -f .first_enabled ] ; then
    mv .first_enabled .enabled
fi

done
 