#!/bin/sh

cat /proc/ls
sleep 0.25

cd $(dirname "$0")

keymon &

touch /tmp/MainUI_exec && sync
while [ -f /tmp/MainUI_exec ]; do
	./MainUI
	
	sysmon fremma
	
	if [ -f /tmp/.cmdenc ] ; then                                                                                   
	    /root/gameloader                                                                                             
	elif [ -f /tmp/cmd_to_run.sh ] ; then                                                                           
	   chmod a+x /tmp/cmd_to_run.sh                                                                                 
	   /tmp/cmd_to_run.sh                                                                                           
	   rm /tmp/cmd_to_run.sh                                                                                        
	fi  

	sysmon fremma
done