#!/bin/sh

# init_lcd
cat /proc/ls
sleep 2

if [ ! -f /customer/lib/libpadsp.so ]; then
 cd /mnt/SDCARD/.tmp_update/.ressources
 ./removed
 reboot
else
	# Waiting background
	cd /mnt/SDCARD/.tmp_update/.ressources
	./installUI &
	sleep 2

	touch /mnt/SDCARD/.tmp_update/.ressources/.unpacked

	# This is a new Onion installation (No BIOS folder yet)
	mkdir /mnt/SDCARD/BIOS

	cd /mnt/SDCARD/RetroArch/.retroarch
	for FILE in ./system/*  
		# Transfering BIOS files		
		do
		mv -R $FILE /mnt/SDCARD/BIOS/
	done

	# Old Rom folder removal
	cd /mnt/SDCARD
	rm -rf RRoms


	if [ -d /mnt/SDCARD/RetroArch/.retroarch/saves ] ; then
		mkdir /mnt/SDCARD/Backup
		mkdir /mnt/SDCARD/Backup/saves
		cd /mnt/SDCARD/RetroArch/.retroarch
		for FILE in ./saves/*  
			# Backup saves just in case someone did not read the README		
			do
			cp -R $FILE /mnt/SDCARD/Backup/saves/
		done
	fi	

	if [ -d /mnt/SDCARD/RetroArch/.retroarch/states ] ; then
		mkdir /mnt/SDCARD/Backup
		mkdir /mnt/SDCARD/Backup/states
		cd /mnt/SDCARD/RetroArch/.retroarch
		for FILE in ./states/*  
			# Backup states just in case someone did not read the README		
			do
			cp -R $FILE /mnt/SDCARD/Backup/states/
		done
	fi

	cd /mnt/SDCARD
	rm -rf RetroArch

	# Debloating the Apps
	cd /mnt/SDCARD/App
	rm -rf Commander_CN
	rm -rf power
	rm -rf RetroArch	

	cd /mnt/SDCARD
	rm -rf Emu
	rm -rf RApp
	rm -rf miyoo
		
	mkdir Emu
	mkdir RApp

	# Onion Core installation / update
	cd "/mnt/SDCARD/.tmp_update/.data"
	for FILE in ./Core/*
		do
		cp -R "$FILE" "/mnt/SDCARD/"
	done

	touch /mnt/SDCARD/.tmp_update/.ressources/.coreInstalled
	sleep 3

	cd /mnt/SDCARD/App/Onion_Manual/
	./launch.sh


	cd /mnt/SDCARD/App/The_Onion_Installer/ 
	./freemma

	# Launch layer manager
	cd /mnt/SDCARD/App/The_Onion_Installer/ 
	./onionInstaller

	cd /mnt/SDCARD/App/The_Onion_Installer/ 
	./freemma

	# force copy the updater for diplaying the manual
	# display turning off message

	cd /mnt/SDCARD/App/Onion_Manual/
	./removed

	cd /mnt/SDCARD/.tmp_update/.ressources
	./boot_mod.sh 

	rm /appconfigs/system.json
	cp /mnt/SDCARD/.tmp_update/.ressources/system.json /appconfigs/system.json

	cd /mnt/SDCARD
	rm -rf .tmp_update

	cd /mnt/SDCARD/Saves
	mv .tmp_update /mnt/SDCARD
	
	# Force refresh the rom lists
	if [ -d /mnt/SDCARD/Roms ] ; then
		cd /mnt/SDCARD/Roms
		find . -type f -name "*.db" -exec rm -f {} \;
	fi
	
	sync
	reboot
	sleep 10
fi

