#!/bin/sh
echo $0 $*
progdir=`cd -- "$(dirname "$0")" >/dev/null 2>&1; pwd -P`

if [ -d /mnt/SDCARD/.tmp_update ]; then
    cd /mnt/SDCARD/.tmp_update
    # Remove everything except dotfiles and onionVersion
    find * -maxdepth 0 -not -name "onionVersion" -exec rm -rf {} \;
fi

cd $progdir
mkdir -p /mnt/SDCARD/.tmp_update
mv .tmp_update/* /mnt/SDCARD/.tmp_update

cd /mnt/SDCARD/.tmp_update
LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/mnt/SDCARD/.tmp_update/lib" ./install.sh

reboot
