#ifndef KEYMAP_H__
#define KEYMAP_H__

#include "SDL/SDL.h"

#define BUTTON_A SDLK_SPACE
#define BUTTON_B SDLK_LCTRL
#define BUTTON_X SDLK_LSHIFT
#define BUTTON_Y SDLK_LALT
#define BUTTON_START SDLK_RETURN
#define BUTTON_SELECT SDLK_RCTRL
#define BUTTON_MENU SDLK_ESCAPE
#define BUTTON_POWER SDLK_POWER
#define BUTTON_L2 SDLK_TAB
#define BUTTON_R2 SDLK_BACKSPACE
#define BUTTON_L1 SDLK_e
#define BUTTON_R1 SDLK_t
#define BUTTON_UP SDLK_UP
#define BUTTON_DOWN SDLK_DOWN
#define BUTTON_LEFT SDLK_LEFT
#define BUTTON_RIGHT SDLK_RIGHT

#endif // KEYMAP_H__