INCLUDE_CJSON=1

include ../common/config.mk

TARGET = emusort
LDFLAGS := $(LDFLAGS) -lSDL -lSDL_ttf -lSDL_image -lSDL_mixer -lSDL_rotozoom -lsqlite3
CFLAGS := $(CFLAGS)

include ../common/commands.mk
include ../common/recipes.mk
